# Do not trigger Travis if commit message contains "(WIP)" or "#no_travis" (case-insensitive)
if: commit_message !~ /(\(WIP\)|#no_travis)/

os: linux

language: python # Can use any language here, but if it's not 'python'
                 # it becomes necessary to pass '--user' to pip when installing hererocks.
python: "3.6"

env:
  - LUA_VERSION=5.3

cache:
  directories:
    # remember to "travis cache --delete" in travis CL each time a custom cached directory needs upgrade (unlike cached packages)
    - hererocks     # for hererocks (make a parent folder, then install lua inside, to make sure the folder will be used as cache)
                    # just a small optimization to cache the whole lua install, since the hererocks pip wheel is cached with .cache/pip anyway
    - tool          # for picotool
    - $HOME/.cache  # for .cache/luarocks and .cache/pip

before_install:
  # install hererocks if needed
  - |
    if [[ ! -d lua$LUA_VERSION || ! -x lua$LUA_VERSION/bin/activate ]]; then
      pip install hererocks
      pushd hererocks
      hererocks lua$LUA_VERSION --lua $LUA_VERSION -rlatest
      popd
    fi

  # activate Lua
  - source hererocks/lua$LUA_VERSION/bin/activate

install:
  # install lua packages for testing
  - luarocks install busted
  - luarocks install luacov

  # delegate submodule install (for luamin from npm, which is tested in test_minify.py)
  - ./setup.sh

before_script:
  # download picotool if needed
  # tool directory is automatically created when added to cache,
  # so it's important to check if the executable itself already exists
  # also download main archive only if not already in cache
  # while this means we may miss some latest version of p8tool,
  # this is fine as it's quite stable for the features we use
  # and we don't need the latest changes specifically
  # if you need to clear cache, do it from Travis or just add some rm main.zip
  - |
    if [[ ! -d tool || ! -x tool/picotool-master/p8tool ]]; then
      pushd tool
      if [[ ! -f main.zip ]]; then
        wget https://github.com/dansanderson/picotool/archive/refs/heads/main.zip
      fi
      unzip main.zip
      popd
    fi
  # make a symlink to p8tool in the PATH
  - mkdir -p "$HOME/.local/bin"
  - ln -s "$(pwd)/tool/picotool-master/p8tool" "$HOME/.local/bin/p8tool"

script:
  # Python test
  - python3 -m scripts.test_add_metadata
  - python3 -m scripts.test_add_require
  - python3 -m scripts.test_minify
  # Lua test
  - ./test.sh -m all
  # Lua coverage
  - bash <(curl -s https://codecov.io/bash)
