require("engine/test/bustedhelper")
require("engine/core/direction_ext")

describe('mirror_dir_x', function ()
  it('should left => right', function ()
    assert.are_equal(directions.right, mirror_dir_x(directions.left))
  end)
  it('should right => left', function ()
    assert.are_equal(directions.left, mirror_dir_x(directions.right))
  end)
  it('should up => up', function ()
    assert.are_equal(directions.up, mirror_dir_x(directions.up))
  end)
  it('should down => down', function ()
    assert.are_equal(directions.down, mirror_dir_x(directions.down))
  end)
end)

describe('+ mirror_dir_y', function ()
  it('should up => down', function ()
    assert.are_equal(directions.down, mirror_dir_y(directions.up))
  end)
  it('should down => up', function ()
    assert.are_equal(directions.up, mirror_dir_y(directions.down))
  end)
  it('should left => left', function ()
    assert.are_equal(directions.left, mirror_dir_y(directions.left))
  end)
  it('should right => right', function ()
    assert.are_equal(directions.right, mirror_dir_y(directions.right))
  end)
end)

describe('rotate_dir_90_cw', function ()
  it('should left => up', function ()
    assert.are_equal(directions.up, rotate_dir_90_cw(directions.left))
  end)
  it('should up => right', function ()
    assert.are_equal(directions.right, rotate_dir_90_cw(directions.up))
  end)
  it('should right => down', function ()
    assert.are_equal(directions.down, rotate_dir_90_cw(directions.right))
  end)
  it('should down => left', function ()
    assert.are_equal(directions.left, rotate_dir_90_cw(directions.down))
  end)
end)

describe('rotate_dir_90_ccw', function ()
  it('should left => down', function ()
    assert.are_equal(directions.down, rotate_dir_90_ccw(directions.left))
  end)
  it('should down => right', function ()
    assert.are_equal(directions.right, rotate_dir_90_ccw(directions.down))
  end)
  it('should right => up', function ()
    assert.are_equal(directions.up, rotate_dir_90_ccw(directions.right))
  end)
  it('should up => left', function ()
    assert.are_equal(directions.left, rotate_dir_90_ccw(directions.up))
  end)
end)
