require("engine/test/bustedhelper")
local string_case = require("engine/core/string_case")

describe('to_big', function ()
  it('"abc" => "abc"', function ()
    assert.are_equal("abc", string_case.to_big("abc"))
  end)
  it('"\65bc" => "abc"', function ()
    assert.are_equal("abc", string_case.to_big("\65bc"))
  end)
  it('"XYZ" => "xyz"', function ()
    assert.are_equal("xyz", string_case.to_big("XYZ"))
  end)
end)
