require("engine/test/bustedhelper")
local time_trigger = require("engine/test/time_trigger")

describe('time_trigger', function ()

  describe('init', function ()
    it('should create a time trigger with a time in seconds using passed fps', function ()
      local time_t = time_trigger(1.0, false, 30)
      assert.is_not_nil(time_t)
      assert.are_equal(time_t.frames, 30)
    end)
    it('should create a time trigger with a time in frames if wanted', function ()
      local time_t = time_trigger(55, true)
      assert.is_not_nil(time_t)
      assert.are_equal(time_t.frames, 55)
    end)
  end)

  describe('_tostring', function ()
    it('should return "time_trigger({self.time})"', function ()
      assert.are_equal("time_trigger(120)", time_trigger(2.0, false, 60):_tostring())
    end)
  end)

  describe('check', function ()
    it('should return true if elapsed time is equal to {self.frames}', function ()
      assert.is_true(time_trigger(2.0, false, 60):check(120))
    end)
    it('should return true if elapsed time is greater than {self.frames}', function ()
      assert.is_true(time_trigger(2.0, false, 60):check(121))
    end)
    it('should return false if elapsed time is less than {self.frames}', function ()
      assert.is_false(time_trigger(2.0, false, 60):check(119))
    end)
  end)

end)
